@baseUrl = http://localhost:8080

@apiKey = {{createAccount.response.body.api_key}}

### Criar uma nova conta
# @name createAccount
POST {{baseUrl}}/accounts
Content-Type: application/json

{
  "name": "John Doe",
  "email": "joh@doe.com"
}

### Obter dados da conta
# @name getAccount
GET {{baseUrl}}/accounts
X-API-Key: {{apiKey}}